config:
    base-health: 20.0
    items:
        enabled: true
        stats:
            strength:
                damage: 0.5
            intelligence: 
                range-damage: 0.5
            dexirity:
                health: 0.2
                armor: 0.2